export const GENDER_OPTIONS = [
    "Man",
    "Woman",
    "Non-binary",
    "Other",
    "Prefer not to say",
];

export const COUNTRIES = [
    { name: "Afghanistan", iso: "af", code: "+93", digits: 9, format: "XX XXX XXXX" },
    { name: "Albania", iso: "al", code: "+355", digits: 9, format: "XX XXX XXXX" },
    { name: "Algeria", iso: "dz", code: "+213", digits: 9, format: "XXX XX XX XX" },
    { name: "Andorra", iso: "ad", code: "+376", digits: 6, format: "XXX XXX" },
    { name: "Angola", iso: "ao", code: "+244", digits: 9, format: "XXX XXX XXX" },
    { name: "Antigua and Barbuda", iso: "ag", code: "+1", digits: 10, format: "XXX XXX XXXX" },
    { name: "Argentina", iso: "ar", code: "+54", digits: 10, format: "XX XXXX XXXX" },
    { name: "Armenia", iso: "am", code: "+374", digits: 8, format: "XX XXX XXX" },
    { name: "Australia", iso: "au", code: "+61", digits: 9, format: "XXX XXX XXX" },
    { name: "Austria", iso: "at", code: "+43", digits: 10, format: "XXX XXX XXXX" },
    { name: "Azerbaijan", iso: "az", code: "+994", digits: 9, format: "XX XXX XXXX" },
    { name: "Bahamas", iso: "bs", code: "+1", digits: 10, format: "XXX XXX XXXX" },
    { name: "Bahrain", iso: "bh", code: "+973", digits: 8, format: "XXXX XXXX" },
    { name: "Bangladesh", iso: "bd", code: "+880", digits: 10, format: "XXXX XXX XXX" },
    { name: "Barbados", iso: "bb", code: "+1", digits: 10, format: "XXX XXX XXXX" },
    { name: "Belarus", iso: "by", code: "+375", digits: 9, format: "XX XXX XXXX" },
    { name: "Belgium", iso: "be", code: "+32", digits: 9, format: "XXX XX XX XX" },
    { name: "Belize", iso: "bz", code: "+501", digits: 7, format: "XXX XXXX" },
    { name: "Benin", iso: "bj", code: "+229", digits: 8, format: "XX XX XX XX" },
    { name: "Bhutan", iso: "bt", code: "+975", digits: 8, format: "XX XXX XXX" },
    { name: "Bolivia", iso: "bo", code: "+591", digits: 8, format: "XXXX XXXX" },
    { name: "Bosnia and Herzegovina", iso: "ba", code: "+387", digits: 8, format: "XX XXX XXX" },
    { name: "Botswana", iso: "bw", code: "+267", digits: 8, format: "XX XXX XXX" },
    { name: "Brazil", iso: "br", code: "+55", digits: 11, format: "XX XXXXX XXXX" },
    { name: "Brunei", iso: "bn", code: "+673", digits: 7, format: "XXX XXXX" },
    { name: "Bulgaria", iso: "bg", code: "+359", digits: 9, format: "XXX XXX XXX" },
    { name: "Burkina Faso", iso: "bf", code: "+226", digits: 8, format: "XX XX XX XX" },
    { name: "Burundi", iso: "bi", code: "+257", digits: 8, format: "XX XX XX XX" },
    { name: "Cabo Verde", iso: "cv", code: "+238", digits: 7, format: "XXX XXXX" },
    { name: "Cambodia", iso: "kh", code: "+855", digits: 9, format: "XX XXX XXXX" },
    { name: "Cameroon", iso: "cm", code: "+237", digits: 9, format: "XXXX XXXXX" },
    { name: "Canada", iso: "ca", code: "+1", digits: 10, format: "XXX XXX XXXX" },
    { name: "Central African Republic", iso: "cf", code: "+236", digits: 8, format: "XX XX XX XX" },
    { name: "Chad", iso: "td", code: "+235", digits: 8, format: "XX XX XX XX" },
    { name: "Chile", iso: "cl", code: "+56", digits: 9, format: "X XXXX XXXX" },
    { name: "China", iso: "cn", code: "+86", digits: 11, format: "XXX XXXX XXXX" },
    { name: "Colombia", iso: "co", code: "+57", digits: 10, format: "XXX XXX XXXX" },
    { name: "Comoros", iso: "km", code: "+269", digits: 7, format: "XXX XXXX" },
    { name: "Congo (Congo-Brazzaville)", iso: "cg", code: "+242", digits: 9, format: "XX XXX XXXX" },
    { name: "Costa Rica", iso: "cr", code: "+506", digits: 8, format: "XXXX XXXX" },
    { name: "Croatia", iso: "hr", code: "+385", digits: 9, format: "XX XXX XXXX" },
    { name: "Cuba", iso: "cu", code: "+53", digits: 8, format: "X XXX XXXX" },
    { name: "Cyprus", iso: "cy", code: "+357", digits: 8, format: "XXXX XXXX" },
    { name: "Czechia (Czech Republic)", iso: "cz", code: "+420", digits: 9, format: "XXX XXX XXX" },
    { name: "Democratic Republic of the Congo", iso: "cd", code: "+243", digits: 9, format: "XXX XXX XXX" },
    { name: "Denmark", iso: "dk", code: "+45", digits: 8, format: "XX XX XX XX" },
    { name: "Djibouti", iso: "dj", code: "+253", digits: 8, format: "XX XX XX XX" },
    { name: "Dominica", iso: "dm", code: "+1", digits: 10, format: "XXX XXX XXXX" },
    { name: "Dominican Republic", iso: "do", code: "+1", digits: 10, format: "XXX XXX XXXX" },
    { name: "Ecuador", iso: "ec", code: "+593", digits: 9, format: "XX XXX XXXX" },
    { name: "Egypt", iso: "eg", code: "+20", digits: 10, format: "XXX XXX XXXX" },
    { name: "El Salvador", iso: "sv", code: "+503", digits: 8, format: "XXXX XXXX" },
    { name: "Equatorial Guinea", iso: "gq", code: "+240", digits: 9, format: "XXX XXX XXX" },
    { name: "Eritrea", iso: "er", code: "+291", digits: 7, format: "X XXX XXX" },
    { name: "Estonia", iso: "ee", code: "+372", digits: 8, format: "XXXX XXXX" },
    { name: "Eswatini", iso: "sz", code: "+268", digits: 8, format: "XXXX XXXX" },
    { name: "Ethiopia", iso: "et", code: "+251", digits: 9, format: "XX XXX XXXX" },
    { name: "Fiji", iso: "fj", code: "+679", digits: 7, format: "XXX XXXX" },
    { name: "Finland", iso: "fi", code: "+358", digits: 9, format: "XXX XXX XXX" },
    { name: "France", iso: "fr", code: "+33", digits: 9, format: "X XX XX XX XX" },
    { name: "Gabon", iso: "ga", code: "+241", digits: 8, format: "X XX XX XX" },
    { name: "Gambia", iso: "gm", code: "+220", digits: 7, format: "XXX XXXX" },
    { name: "Georgia", iso: "ge", code: "+995", digits: 9, format: "XXX XXX XXX" },
    { name: "Germany", iso: "de", code: "+49", digits: 10, format: "XXXX XXXXXX" },
    { name: "Ghana", iso: "gh", code: "+233", digits: 9, format: "XX XXX XXXX" },
    { name: "Greece", iso: "gr", code: "+30", digits: 10, format: "XXX XXX XXXX" },
    { name: "Grenada", iso: "gd", code: "+1", digits: 10, format: "XXX XXX XXXX" },
    { name: "Guatemala", iso: "gt", code: "+502", digits: 8, format: "XXXX XXXX" },
    { name: "Guinea", iso: "gn", code: "+224", digits: 9, format: "XXX XXX XXX" },
    { name: "Guinea-Bissau", iso: "gw", code: "+245", digits: 9, format: "XXX XXX XXX" },
    { name: "Guyana", iso: "gy", code: "+592", digits: 7, format: "XXX XXXX" },
    { name: "Haiti", iso: "ht", code: "+509", digits: 8, format: "XXXX XXXX" },
    { name: "Honduras", iso: "hn", code: "+504", digits: 8, format: "XXXX XXXX" },
    { name: "Hungary", iso: "hu", code: "+36", digits: 9, format: "XX XXX XXXX" },
    { name: "Iceland", iso: "is", code: "+354", digits: 7, format: "XXX XXXX" },
    { name: "India", iso: "in", code: "+91", digits: 10, format: "XXXXX XXXXX" },
    { name: "Indonesia", iso: "id", code: "+62", digits: 10, format: "XXX XXXX XXXX" },
    { name: "Iran", iso: "ir", code: "+98", digits: 10, format: "XXX XXX XXXX" },
    { name: "Iraq", iso: "iq", code: "+964", digits: 10, format: "XXX XXX XXXX" },
    { name: "Ireland", iso: "ie", code: "+353", digits: 9, format: "XX XXX XXXX" },
    { name: "Israel", iso: "il", code: "+972", digits: 9, format: "XX XXX XXXX" },
    { name: "Italy", iso: "it", code: "+39", digits: 10, format: "XXX XXX XXXX" },
    { name: "Jamaica", iso: "jm", code: "+1", digits: 10, format: "XXX XXX XXXX" },
    { name: "Japan", iso: "jp", code: "+81", digits: 10, format: "XX XXXX XXXX" },
    { name: "Jordan", iso: "jo", code: "+962", digits: 9, format: "X XXX XXXX" },
    { name: "Kazakhstan", iso: "kz", code: "+7", digits: 10, format: "XXX XXX XXXX" },
    { name: "Kenya", iso: "ke", code: "+254", digits: 9, format: "XXX XXX XXX" },
    { name: "Kiribati", iso: "ki", code: "+686", digits: 8, format: "XXXX XXXX" },
    { name: "Kuwait", iso: "kw", code: "+965", digits: 8, format: "XXXX XXXX" },
    { name: "Kyrgyzstan", iso: "kg", code: "+996", digits: 9, format: "XXX XXX XXX" },
    { name: "Laos", iso: "la", code: "+856", digits: 9, format: "XX XXX XXXX" },
    { name: "Latvia", iso: "lv", code: "+371", digits: 8, format: "XXXX XXXX" },
    { name: "Lebanon", iso: "lb", code: "+961", digits: 8, format: "XX XXX XXX" },
    { name: "Lesotho", iso: "ls", code: "+266", digits: 8, format: "XXXX XXXX" },
    { name: "Liberia", iso: "lr", code: "+231", digits: 8, format: "XX XXX XXX" },
    { name: "Libya", iso: "ly", code: "+218", digits: 9, format: "XX XXX XXXX" },
    { name: "Liechtenstein", iso: "li", code: "+423", digits: 7, format: "XXX XXXX" },
    { name: "Lithuania", iso: "lt", code: "+370", digits: 8, format: "XXXX XXXX" },
    { name: "Luxembourg", iso: "lu", code: "+352", digits: 9, format: "XXX XXX XXX" },
    { name: "Madagascar", iso: "mg", code: "+261", digits: 9, format: "XX XX XXX XX" },
    { name: "Malawi", iso: "mw", code: "+265", digits: 9, format: "XX XXX XXXX" },
    { name: "Malaysia", iso: "my", code: "+60", digits: 9, format: "XX XXXX XXXX" },
    { name: "Maldives", iso: "mv", code: "+960", digits: 7, format: "XXX XXXX" },
    { name: "Mali", iso: "ml", code: "+223", digits: 8, format: "XX XX XX XX" },
    { name: "Malta", iso: "mt", code: "+356", digits: 8, format: "XXXX XXXX" },
    { name: "Marshall Islands", iso: "mh", code: "+692", digits: 7, format: "XXX XXXX" },
    { name: "Mauritania", iso: "mr", code: "+222", digits: 8, format: "XXXX XXXX" },
    { name: "Mauritius", iso: "mu", code: "+230", digits: 8, format: "XXXX XXXX" },
    { name: "Mexico", iso: "mx", code: "+52", digits: 10, format: "XXX XXX XXXX" },
    { name: "Micronesia", iso: "fm", code: "+691", digits: 7, format: "XXX XXXX" },
    { name: "Moldova", iso: "md", code: "+373", digits: 8, format: "XXXX XXXX" },
    { name: "Monaco", iso: "mc", code: "+377", digits: 8, format: "XXXX XXXX" },
    { name: "Mongolia", iso: "mn", code: "+976", digits: 8, format: "XXXX XXXX" },
    { name: "Montenegro", iso: "me", code: "+382", digits: 8, format: "XX XXX XXX" },
    { name: "Morocco", iso: "ma", code: "+212", digits: 9, format: "XXX XXX XXX" },
    { name: "Mozambique", iso: "mz", code: "+258", digits: 9, format: "XX XXX XXXX" },
    { name: "Myanmar (Burma)", iso: "mm", code: "+95", digits: 9, format: "XX XXX XXXX" },
    { name: "Namibia", iso: "na", code: "+264", digits: 9, format: "XX XXX XXXX" },
    { name: "Nauru", iso: "nr", code: "+674", digits: 7, format: "XXX XXXX" },
    { name: "Nepal", iso: "np", code: "+977", digits: 10, format: "XXX XXX XXXX" },
    { name: "Netherlands", iso: "nl", code: "+31", digits: 9, format: "X XX XX XX XX" },
    { name: "New Zealand", iso: "nz", code: "+64", digits: 9, format: "XX XXX XXXX" },
    { name: "Nicaragua", iso: "ni", code: "+505", digits: 8, format: "XXXX XXXX" },
    { name: "Niger", iso: "ne", code: "+227", digits: 8, format: "XX XX XX XX" },
    { name: "Nigeria", iso: "ng", code: "+234", digits: 10, format: "XXX XXX XXXX" },
    { name: "North Korea", iso: "kp", code: "+850", digits: 8, format: "XXXX XXXX" },
    { name: "North Macedonia", iso: "mk", code: "+389", digits: 8, format: "XX XXX XXX" },
    { name: "Norway", iso: "no", code: "+47", digits: 8, format: "XX XX XX XX" },
    { name: "Oman", iso: "om", code: "+968", digits: 8, format: "XXXX XXXX" },
    { name: "Pakistan", iso: "pk", code: "+92", digits: 10, format: "XXX XXX XXXX" },
    { name: "Palau", iso: "pw", code: "+680", digits: 7, format: "XXX XXXX" },
    { name: "Palestine State", iso: "ps", code: "+970", digits: 9, format: "XXX XXX XXX" },
    { name: "Panama", iso: "pa", code: "+507", digits: 8, format: "XXXX XXXX" },
    { name: "Papua New Guinea", iso: "pg", code: "+675", digits: 8, format: "XXXX XXXX" },
    { name: "Paraguay", iso: "py", code: "+595", digits: 9, format: "XXX XXX XXX" },
    { name: "Peru", iso: "pe", code: "+51", digits: 9, format: "XXX XXX XXX" },
    { name: "Philippines", iso: "ph", code: "+63", digits: 10, format: "XXX XXX XXXX" },
    { name: "Poland", iso: "pl", code: "+48", digits: 9, format: "XXX XXX XXX" },
    { name: "Portugal", iso: "pt", code: "+351", digits: 9, format: "XXX XXX XXX" },
    { name: "Qatar", iso: "qa", code: "+974", digits: 8, format: "XXXX XXXX" },
    { name: "Romania", iso: "ro", code: "+40", digits: 9, format: "XXX XXX XXX" },
    { name: "Russia", iso: "ru", code: "+7", digits: 10, format: "XXX XXX XX XX" },
    { name: "Rwanda", iso: "rw", code: "+250", digits: 9, format: "XXX XXX XXX" },
    { name: "Saint Kitts and Nevis", iso: "kn", code: "+1", digits: 10, format: "XXX XXX XXXX" },
    { name: "Saint Lucia", iso: "lc", code: "+1", digits: 10, format: "XXX XXX XXXX" },
    { name: "Saint Vincent and the Grenadines", iso: "vc", code: "+1", digits: 10, format: "XXX XXX XXXX" },
    { name: "Samoa", iso: "ws", code: "+685", digits: 7, format: "XX XXXXX" },
    { name: "San Marino", iso: "sm", code: "+378", digits: 8, format: "XXXX XXXX" },
    { name: "Sao Tome and Principe", iso: "st", code: "+239", digits: 7, format: "XXX XXXX" },
    { name: "Saudi Arabia", iso: "sa", code: "+966", digits: 9, format: "XX XXX XXXX" },
    { name: "Senegal", iso: "sn", code: "+221", digits: 9, format: "XX XXX XXXX" },
    { name: "Serbia", iso: "rs", code: "+381", digits: 9, format: "XX XXX XXXX" },
    { name: "Seychelles", iso: "sc", code: "+248", digits: 7, format: "X XX XXXX" },
    { name: "Sierra Leone", iso: "sl", code: "+232", digits: 8, format: "XX XXX XXX" },
    { name: "Singapore", iso: "sg", code: "+65", digits: 8, format: "XXXX XXXX" },
    { name: "Slovakia", iso: "sk", code: "+421", digits: 9, format: "XXX XXX XXX" },
    { name: "Slovenia", iso: "si", code: "+386", digits: 8, format: "XX XXX XXX" },
    { name: "Solomon Islands", iso: "sb", code: "+677", digits: 7, format: "XXX XXXX" },
    { name: "Somalia", iso: "so", code: "+252", digits: 8, format: "XX XXX XXX" },
    { name: "South Africa", iso: "za", code: "+27", digits: 9, format: "XX XXX XXXX" },
    { name: "South Korea", iso: "kr", code: "+82", digits: 10, format: "XX XXXX XXXX" },
    { name: "South Sudan", iso: "ss", code: "+211", digits: 9, format: "XX XXX XXXX" },
    { name: "Spain", iso: "es", code: "+34", digits: 9, format: "XXX XXX XXX" },
    { name: "Sri Lanka", iso: "lk", code: "+94", digits: 9, format: "XX XXX XXXX" },
    { name: "Sudan", iso: "sd", code: "+249", digits: 9, format: "XX XXX XXXX" },
    { name: "Suriname", iso: "sr", code: "+597", digits: 7, format: "XXX XXXX" },
    { name: "Sweden", iso: "se", code: "+46", digits: 9, format: "XXX XXX XXX" },
    { name: "Switzerland", iso: "ch", code: "+41", digits: 9, format: "XX XXX XXXX" },
    { name: "Syria", iso: "sy", code: "+963", digits: 9, format: "XX XXX XXXX" },
    { name: "Tajikistan", iso: "tj", code: "+992", digits: 9, format: "XX XXX XXXX" },
    { name: "Tanzania", iso: "tz", code: "+255", digits: 9, format: "XXX XXX XXX" },
    { name: "Thailand", iso: "th", code: "+66", digits: 9, format: "XX XXX XXXX" },
    { name: "Timor-Leste", iso: "tl", code: "+670", digits: 8, format: "XXXX XXXX" },
    { name: "Togo", iso: "tg", code: "+228", digits: 8, format: "XX XX XX XX" },
    { name: "Tonga", iso: "to", code: "+676", digits: 7, format: "XXX XXXX" },
    { name: "Trinidad and Tobago", iso: "tt", code: "+1", digits: 10, format: "XXX XXX XXXX" },
    { name: "Tunisia", iso: "tn", code: "+216", digits: 8, format: "XX XXX XXX" },
    { name: "Turkey", iso: "tr", code: "+90", digits: 10, format: "XXX XXX XXXX" },
    { name: "Turkmenistan", iso: "tm", code: "+993", digits: 8, format: "XXXX XXXX" },
    { name: "Tuvalu", iso: "tv", code: "+688", digits: 6, format: "XX XXXX" },
    { name: "Uganda", iso: "ug", code: "+256", digits: 9, format: "XXX XXX XXX" },
    { name: "Ukraine", iso: "ua", code: "+380", digits: 9, format: "XX XXX XXXX" },
    { name: "United Arab Emirates", iso: "ae", code: "+971", digits: 9, format: "XX XXX XXXX" },
    { name: "United Kingdom", iso: "gb", code: "+44", digits: 10, format: "XXXXX XXXXX" },
    { name: "United States", iso: "us", code: "+1", digits: 10, format: "XXX XXX XXXX" },
    { name: "Uruguay", iso: "uy", code: "+598", digits: 8, format: "XXXX XXXX" },
    { name: "Uzbekistan", iso: "uz", code: "+998", digits: 9, format: "XX XXX XXXX" },
    { name: "Vanuatu", iso: "vu", code: "+678", digits: 7, format: "XXX XXXX" },
    { name: "Venezuela", iso: "ve", code: "+58", digits: 10, format: "XXX XXX XXXX" },
    { name: "Vietnam", iso: "vn", code: "+84", digits: 9, format: "XXX XXX XXX" },
    { name: "Yemen", iso: "ye", code: "+967", digits: 9, format: "XXX XXX XXX" },
    { name: "Zambia", iso: "zm", code: "+260", digits: 9, format: "XX XXX XXXX" },
    { name: "Zimbabwe", iso: "zw", code: "+263", digits: 9, format: "XX XXX XXXX" },
];

export function formatPhoneNumber(digits, format) {
    let result = '';
    let digitIndex = 0;
    for (let i = 0; i < format.length; i++) {
        if (format[i] === 'X') {
            if (digitIndex < digits.length) {
                result += digits[digitIndex++];
            } else {
                break;
            }
        } else {
            if (digitIndex < digits.length) {
                result += format[i];
            }
        }
    }
    return result;
}